# Generated by Django 5.2.3 on 2025-06-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlangSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slang', models.TextField(blank=True, null=True)),
                ('slang_word', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
